services:
  api:
    build: .
    ports: ["8000:8000"]
    environment:
      API_KEY: ${API_KEY:-dev-key}
      GOOGLE_CLOUD_PROJECT: ${GOOGLE_CLOUD_PROJECT:?set in .env}
      BQ_DATASET: ${BQ_DATASET:-demo_vectors}
      BQ_LOCATION: ${BQ_LOCATION:-US}
      GOOGLE_APPLICATION_CREDENTIALS: /secrets/key.json
    volumes:
      - ./secrets/key.json:/secrets/key.json:ro
    command: gunicorn -w 2 --preload -b 0.0.0.0:8000 app.main:app
